# Generated by Django 5.1.4 on 2024-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('nome', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('senha', models.CharField(max_length=1024)),
            ],
        ),
    ]
