# Generated by Django 5.1.4 on 2024-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceravi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
